# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-12 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbof', '0002_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='Undefined', max_length=500),
        ),
    ]
