# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mbof.models


class Migration(migrations.Migration):

    dependencies = [
        ('mbof', '0004_event_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intention', models.CharField(choices=[('going', 'going'), ('maybe', 'maybe')], max_length=5)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbof.Event')),
                ('respondent', models.ForeignKey(default=mbof.models.currentUserObject, editable=False, on_delete=django.db.models.deletion.CASCADE, to='mbof.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='intention',
            unique_together=set([('event', 'respondent')]),
        ),
    ]
