# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbof', '0005_auto_20160718_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intention',
            name='intention',
            field=models.CharField(choices=[('going', 'going'), ('maybe', 'maybe'), ('declined', 'declined')], max_length=8),
        ),
    ]
