# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-17 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbof', '0006_auto_20160816_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intention',
            name='intention',
            field=models.CharField(choices=[('going', 'going'), ('maybe', 'maybe'), ('declined', 'declined')], max_length=10),
        ),
    ]
