# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbof', '0007_auto_20160817_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.CharField(max_length=8),
        ),
    ]
