# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbof', '0008_auto_20160915_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.CharField(db_column='owner', editable=False, max_length=8),
        ),
        migrations.AlterField(
            model_name='intention',
            name='respondent',
            field=models.CharField(db_column='respondent', editable=False, max_length=8),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.CharField(db_column='voter', editable=False, max_length=8),
        ),
    ]
