# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbof', '0009_auto_20160913_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intention',
            name='respondent',
            field=models.CharField(editable=False, max_length=8),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.CharField(editable=False, max_length=8),
        ),
    ]
