# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbof', '0009_auto_20160915_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
